language: objective-c
osx_image: xcode9.3
xcode_project: LazyViewContainer.xcodeproj
xcode_scheme: LazyViewContainer
xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=LazyViewContainer
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - xcodebuild clean build -sdk iphonesimulator -project LazyViewContainer.xcodeproj -scheme LazyViewContainer
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: LazyViewContainer.framework.zip
  skip_cleanup: true
  on:
    tags: true
